FROM elasticsearch:6.5.4
MAINTAINER nayuan <nayuan@vip.qq.com>

# RUN rm /usr/share/elasticsearch/modules/x-pack-core/x-pack-core-6.4.2.jar
# COPY x-pack-core-6.5.4.jar /usr/share/elasticsearch/modules/x-pack-core/

