FROM registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:0.9.5-filebeat
MAINTAINER nayuan <nayuan@vip.qq.com>

RUN echo 172.18.200.214 node-kafka-01 >> /etc/hosts && \
    echo 172.18.200.214 node-kafka-02 >> /etc/hosts